### ISSUE TITLE
Declare directory for notes

### ISSUE THREAD

**Issue by ErikPrantare** [debanjum/khoj#110]
Cool project! This looks very much like what I need for searching my notes.

Currently it seems like I have to select each and every note I want to index.
This becomes problematic when using something like org-roam,
where a new note will get a new file.
I currently have about 1.5k files, so having to select new ones manually is suboptimal.
Being able to simply select the not directory,
and then have khoj update whenever new files are added would be great.

**Comment by debanjum** [comment]
Hi @ErikPrantare, thanks for the feedback!

> Currently it seems like I have to select each and every note I want to index.

The Desktop UI doesn't expose this capability (yet). But you can update the underlying `~/.khoj/khoj.yml` config file to index org files under your org-roam directory (recursively) by setting `content-type > org > input-filter` field to the [glob pattern](https://docs.python.org/3/library/glob.html) of `/path/to/your/org-roam-notes/**/*.org` like so: <img width="574" alt="set-directory-for-notes-in-khoj-yml" src="https://user-images.githubusercontent.com/6413477/210706699-1bfb9781-8009-45d8-94c2-cf2e2ccc64fa.png">

> have khoj update whenever new files are added would be great.

The capability to automatically index new content was just [released earlier today](https://github.com/debanjum/khoj/releases/tag/0.2.1)! Do try it out and let me know if you hit any further issues 😇

**Comment by ErikPrantare** [comment]
Nice, that is just what I looked for.

**Comment by debanjum** [comment]
Great! I'll resolve the issue in that case. 

Feel free to re-open it, if indexing your org-roam directory with khoj doesn't work
