### ISSUE TITLE
Higher contrast for web interface

### ISSUE THREAD

**Issue by ErikPrantare** [debanjum/khoj#111]
Currently the contrast in the web interface is very low for me.
Perhaps consider getting inspiration from the WCAG for theming?

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

**Comment by debanjum** [comment]
You mean the contrast between text and the background on the web interface or something else/more?

Thanks for the feedback and an official link! Let me have a deeper look at it soon and find some tool to give me the current contrast ratio numbers for the khoj web interface.

**Comment by ErikPrantare** [comment]
Yeah, specifically the search results and the background :)
