### ISSUE TITLE
Issue using Khoj on Windows 11 installed through WSL

### ISSUE THREAD

**Issue by matthew-boyens** [debanjum/khoj#156]
When I install khoj in my wsl linux environment, it automatically appends the location of my obsidian vault to ~/.khoj/khoj.yml in windows path format not linux. 

I understand my setup is unique, but any tips for how I could adjust the config file so it points to the correct location?

![image](https://user-images.githubusercontent.com/48612311/218361551-8a29d2fc-dbdc-4a8a-929d-1496c65e6f8b.png)

Config after turning on the obsidian plugin

![image](https://user-images.githubusercontent.com/48612311/218362010-c581a09b-dbc0-41b3-909c-4bae37e188b6.png)

My attempt at modifying the config 

![image](https://user-images.githubusercontent.com/48612311/218361659-4766aec4-6915-4308-9c82-b6a64d7b6238.png)

Returns this after change

![image](https://user-images.githubusercontent.com/48612311/218361722-141e1ed8-692a-4a76-8714-9931fdfda107.png)

Perhaps I need to just install it outside of wsl, but I would like to avoid that if possible

Thanks

**Comment by debanjum** [comment]
Ah interesting. Yeah, that's not a scenario I'd originally thought off. 

Currently the khoj obsidian plugin (crudely) overwrites any existing configuration of the markdown content-type in your `khoj.yml`. So the changes you are manually making to your `~/.khoj/khoj.yml` are getting overridden when Obsidian is started or the plugin is installed/reloaded.

I can add a toggle in the plugin setting to enable/disable automatically configuring the khoj backend from the plugin. 
You can then disable auto-configure from the khoj plugin settings in Obsidian and manually set the vault(s) to index in your `khoj.yml`. Would that suffice for your use-case?

**Comment by matthew-boyens** [comment]
That sounds like that would work, thanks a lot!

**Comment by debanjum** [comment]
Added a toggle in the plugin settings to enable/disable auto configuring the khoj backend from the plugin.
<img width="767" alt="auto_configure_toggle_in_khoj_obsidian" src="https://user-images.githubusercontent.com/6413477/218622440-151800e6-3ea5-4924-a42e-97d720582fe2.png">

Unless you're willing to run the plugin from source. You'll have to wait till I create a new release for khoj, hopefully by the end of this week.

Feel free to re-open this issue if the auto-configure settings toggle doesn't satisfy your use-case
