### ISSUE TITLE
Daemon (background service)

### ISSUE THREAD

**Issue by zcysxy** [debanjum/khoj#162]
Hi, thanks for this creative program! Now to use it, we need to keep a terminal window open. Would it be possible to turn it into a daemon (background service)? Although this should not take priority, I think it is a QoL improvement.

**Comment by debanjum** [comment]
Yeah, having to keep the terminal window open (and manually start the application on reboot) is annoying.
You can solve this by starting `khoj` using crontab or the Windows Task Manager at reboot. 
See [these sample instructions](https://medium.com/analytics-vidhya/easiest-way-to-run-a-python-script-in-the-background-4aada206cf29) for more details.

This should hopefully solve the issue. But let me know if that doesn't work for your use-case?
I'll update the readme with these instructions if it works for you

**Comment by zcysxy** [comment]
Didn't know such command exists. Thank you very much! Another method, run the following command instead (on macOS/Linux)

```shell
bash -c "nohup /path/to/khoj --no-gui &"
```

Reference: https://stackoverflow.com/questions/32243553/running-process-in-background-after-closing-terminal

**Comment by debanjum** [comment]
>  Another method, run the following command instead (on macOS/Linux)
> ```shell
> bash -c "nohup /path/to/khoj --no-gui &"
> ```

Ah yes, forgot to mention, your above command should suffice if you just want to run khoj in the background. 
You can close your terminal after running that command and khoj will keep running.

Cron/Task Scheduler are useful if you also want to start khoj in background on machine reboot
