### ISSUE TITLE
[org-roam/org] khoj don't detect information under the title when the file contains a heading

### ISSUE THREAD

**Issue by Cletip** [debanjum/khoj#165]
Hi!
I noticed that if the file contains a heading, then what is between the "#+title:" and the first heading is simply... untraceable. Impossible to find this information in khoj. On the other hand, if the file does not contain any heading (and thus, only #+title: and text), then the information is retrievable. For example, for this :

```
#+title: A nice title

An information here : A

* Title one here

Another information here : B
```

Khoj will never find information A.

Thanks you in advance for your futur answer.

**Comment by debanjum** [comment]
Thanks for opening an issue for this! This seems like a bug. Let me try reproduce the issue on my end.

**Comment by debanjum** [comment]
Hi @Cletip, I've pushed a fix for this issue you found in https://github.com/debanjum/khoj/commit/fe03ba3dcee9cefbc4bba076009ba1a711f68880. 
Khoj should index intro text before headings in org files too now.
Let me know if the issue is resolved for you with the latest pre-release khoj. 
You can update your khoj server with `pip install --upgrade --pre khoj-assistant`

**Comment by Cletip** [comment]
Hi @debanjum 

I did the update command, and I get the following error when I want to start khoj: 
```
Traceback (most recent call last):
  File "/home/utilisateur/.local/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/home/utilisateur/.local/lib/python3.8/site-packages/khoj/main.py", line 78, in run
    main_window = MainWindow(args.config_file)
  File "/home/utilisateur/.local/lib/python3.8/site-packages/khoj/interface/desktop/main_window.py", line 61, in __init__
    current_content_config = self.current_config["content-type"][search_type] or self.get_default_config(
KeyError: <SearchType.Ledger: 'ledger'>
```

**Comment by debanjum** [comment]
Interesting, looks like a bug. 
- Did you manually edit your khoj.yml file or did you use the GUI to configure khoj?
- Can you share how your `khoj.yml` file looks? It should be located at `~/.khoj/khoj.yml`

**Comment by debanjum** [comment]
Never mind, thanks to the error logs you already shared I was able to reproduce the bug you hit on my end.
It occurs when content-type > ledger (or any other expected content-type section) isn't defined in `khoj.yml`

 I've just pushed a fix for the issue. It'd be great if you can update you khoj with `pip install --upgrade --pre khoj-assistant` and see if that resolves the issue

**Comment by Cletip** [comment]
Wow, thanks for your message and the little improvements (the emojys are nice).

I did the test again, and khoj finds all the information well, no matter where it is. Thank you very much for your speed!

**Comment by debanjum** [comment]
No problem, glad Khoj works well for you now!
