### ISSUE TITLE
Obsidian Plugin link and dataview errors

### ISSUE THREAD

**Issue by ggstrader** [debanjum/khoj#177]
I've finally got the server running and linked with Obsidian. Search seems to work, but I can't navigate to any of the results. The console logs the following errors 6 times (one for each result) when typing one character:
![image](https://user-images.githubusercontent.com/101308963/222319197-72c36902-c016-4b6e-9f78-918cf005fa7a.png)
**Windows 10
Obsidian 1.1.15
Khoj 0.3.0**

**Comment by debanjum** [comment]
Hey @ggstrader, thanks for opening a bug (with error from console log) for this. Just wanted to clarify:
- When you say that search seems to work, do you mean you see some results in your Khoj search modal?
- Is the issue that you cannot navigate to the results within the search modal (e.g with the arrow keys) or that you cannot jump to the markdown note from the results in the search modal (e.g by hitting Enter while on a result in khoj search modal)?

**Comment by ggstrader** [comment]
The results show up, but clicking or hitting enter does nothing

**Comment by debanjum** [comment]
Hey @ggstrader, I've fixed the issue with jumping to the note corresponding to the khoj search result in https://github.com/debanjum/khoj/commit/4fb628975c41cd1a38f2eb1a53993d4368d7b2f6.

This fix should become available as an update to the Khoj Obsidian plugin when I make the next Khoj release (which I'll publish in a few days).
