### ISSUE TITLE
Parent directory error

### ISSUE THREAD

**Issue by jk-oster** [debanjum/khoj#185]
Hi, thanks a lot for creating this awesome tool. The installation was no problem after installing the correct python version on Windows. 

I am using Khoj with obsidian and used the automatic configuration from the obsidian plugin. My vault is located in the directory `C:\Users\joste\Documents\_Persönlich\Obsidian\2nd Brain`. After start up and completing the batches, I got the following error and couldn't find a solution yet after doing some research.

```
Traceback (most recent call last):
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\Scripts\khoj.exe\__main__.py", line 7, in <module>
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\main.py", line 88, in run
    configure_server(args, required=False)
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 48, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\configure.py", line 113, in configure_search
    model.markdown_search = text_search.setup(
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\search_type\text_search.py", line 179, in setup
    corpus_embeddings = compute_embeddings(
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\khoj\search_type\text_search.py", line 96, in compute_embeddings
    torch.save(corpus_embeddings, embeddings_file)
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\Users\joste\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory C:\Users\joste\Users\joste\Documents\_Persönlich\Obsidian does not exist.
```

Somehow the path ended up wrong. Do you have any idea if there is some possible configuration issue or a problem with the path I am using for my vault?

Here is part of the configuration that has been created, which seems fine to me:

```
content-type:
  image: null
  ledger: null
  markdown:
    compressed-jsonl: "~\\.khoj\\content\\markdown\\C:\\Users\\joste\\Documents\\\
      _Pers\xF6nlich\\Obsidian\\2nd_Brain.jsonl.gz"
    embeddings-file: "~\\.khoj\\content\\markdown\\C:\\Users\\joste\\Documents\\_Pers\xF6\
      nlich\\Obsidian\\2nd_Brain.pt"
    index-heading-entries: false
    input-files: null
    input-filter:
    - "C:\\Users\\joste\\Documents\\_Pers\xF6nlich\\Obsidian\\2nd Brain/**/*.md"
  music: null
  org: null
  plugins: null
```

I'd be grateful for some help to get Khoj running.

**Comment by debanjum** [comment]
> I am using Khoj with obsidian and used the automatic configuration from the obsidian plugin. My vault is located in the directory C:\Users\joste\Documents\_Persönlich\Obsidian\2nd Brain.

Hey @jk-oster, thanks for providing some context (like khoj.yml and your actual vault directory path) to debug this issue. 

> RuntimeError: Parent directory C:\Users\joste\Users\joste\Documents\_Persönlich\Obsidian does not exist.

The umlaut in your directory path maybe messing with khoj `C:\Users\joste\Documents_Persönlich\Obsidian\2nd Brain`
Let me try reproduce this issue (and if required, ask you for more details)

Also the paths that have been set in your `khoj.yml` config look weird too. E.g `~\\.khoj\\content\\markdown\C:\\...`

For a (potential) quick fix to start using Khoj:
1. Turn off the automatic configuration in the Khoj Obsidian plugin settings
    This requires manual maintainance of your khoj.yml for now (instead of having the Khoj Obsidian plugin maintain it)
2. Delete the `C:\\Users\joste\\.khoj\\content` directory, if it exists on your system
2. Update the `content-type` section in your khoj.yml to look something like:
    ```yaml
    content-type:
      image: null
      ledger: null
      markdown:
        compressed-jsonl: "C:\\Users\\joste\\.khoj\\content\\markdown\\2nd_Brain.jsonl.gz"
        embeddings-file: "C:\\Users\\joste\\.khoj\\content\\markdown\\2nd_Brain.pt"
        index-heading-entries: false
        input-files: null
        input-filter:
        - "C:\\Users\\joste\\Documents_Persönlich\\Obsidian\\2nd Brain/**/*.md"
      music: null
      org: null
      plugins: null
    ```
3. Restart the Khoj server/backend

Let me know if that mitigates the issue for you?


*Sidenote (for me): Khoj path handling on Windows needs (more) testing.*

**Comment by debanjum** [comment]
Hey @jk-oster,

I was able to reproduce the issue you were facing in using Khoj with Obsidian on Windows.
I've pushed a fix for it to the main branch. I'll create a minor release for it in a day or two. 

At that point, if you upgrade your khoj server and obsidian plugin you should (hopefully) have this issue resolved with having to turn of the auto-configuration in khoj obsidian plugin settings.

Let me know if that doesn't resolve your issue
