### ISSUE TITLE
[Bug] Qt error while building Docker image

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#200]
This is the stack trace:
```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
```

I'm able to reproduce it locally. Specifically encountered when building with the PyQT gui.

**Comment by sabaimran** [comment]
Ah, I used the env variable `QT_DEBUG_PLUGINS=1` to get more information. All the libraries load fine, but the Qt application can't seem to access the display in the Docker container.
```
server_1  | qt.qpa.xcb: could not connect to display
```

The image seems to work fine without the GUI, but I wonder if there's a way to get it working within the Docker container.

**Comment by sabaimran** [comment]
It looks like [these instructions](https://mindup.medium.com/running-gui-apps-securely-in-docker-sandbox-5d945288929b) might be useful in getting this working, but currently don't feel it's worth the effort required to get unblocked. Hopefully using Khoj without the GUI with Docker is sufficient for the moment :-)

**Comment by debanjum** [comment]
Yeah, I think installing `xcb` is required. See the `docker.yml` github workflow for example of setup
