### ISSUE TITLE
help text on improve search results

### ISSUE THREAD

**Issue by whatSocks** [debanjum/khoj#207]
what are some strategies for improving search results? For some more popular concepts, it seems like the search results are good - but very frequently if I use the search for the title of a note it doesn't find it, or any notes related to it

**Comment by debanjum** [comment]
Umm, I recently updated khoj to index the title/filename of markdown note in https://github.com/debanjum/khoj/commit/a2ab68a7a2f0d7e0397051a54b5fd67a4052d907. Can you share which version of khoj you are on (i.e execute `khoj --version` in terminal) ? Are using khoj with markdown/obsidian?

**Comment by debanjum** [comment]
To improve search quality you can try: 
 1. Use natural language queries that are longer than the usual keyword based search queries . E.g *"visited national park, saw animals"* vs *"national park cheetah"*
 2. Rerank the results after you've entered your query in the Khoj Search Modal on Obsidian (with Cmd+Enter or Ctrl+Enter). This should improve ranking quality of results (it uses a slower but better model for reranking)
 3. Add word, date or file filters to the query to filter results. See *Query Filters* under [Khoj search](https://github.com/debanjum/khoj#Khoj-search) section in Readme for usage

**Comment by debanjum** [comment]
Ah, good to know re-indexing your Vault fixed the issue. There is some intermittent index corruption issue, which I've not been able to reproduce and hence fix yet. Seems like it may have affected you.

Good idea on finding a more direct way of notifying users. Can you expand on what you mean by adding help text?

**Comment by whatSocks** [comment]
<img width="716" alt="Screenshot 2023-04-08 at 12 52 04 PM" src="https://user-images.githubusercontent.com/2731744/230733343-a04d25f4-1bf7-4d5b-be7d-485914b3a2c0.png">

Maybe here under the search bar put

_results not what you expected? Try re-indexing your vault._"

**Comment by debanjum** [comment]
I see, thanks for the idea! Let me see what can be done to suggest re-indexing vault if search results are not good anymore
