### ISSUE TITLE
Interactive configurer for non-technical users

### ISSUE THREAD

**Issue by khayyamsaleem** [debanjum/khoj#210]
I'm sure some Obsidian users would be more comfortable selecting a model from the UI and launching the daemon from an interactive configuration utility, rather than manually editing the khoj.yml and running commands.

**Comment by debanjum** [comment]
I agree! Can you clarify what you specifically find lacking in the current (set of) UIs? 
Knowing concrete pain points will help guide simplifying setup of khoj for non-technical users.

I've listed some options currently available and some planned improvements I was thinking of working on below:

### What current exists
1. The Khoj obsidian plugin automatically configures the server with a standard configuration. So most users shouldn't have to manually configure the server themselves. They do have to manually install and start the server
2. The Khoj server provides a GUI to configure it (i.e if you start khoj server by running `khoj`)
3. The Khoj web interface exposes a basic UI to configure the khoj server (at `http://khoj-web-url/config`) though it hasn't been socialized yet. This could be ported for use from within Obsidian directly (e.g selecting different models)
4. The Khoj server also has standard GUI apps for each operating systems. See [release assets](https://github.com/debanjum/khoj/releases). These can remove the need to open a terminal to install Khoj. And it exposes a UI to configure the server. These apps need to be socialized and tested.
 
### What needs to be created
Removing the need for Obsidian users to open a terminal to install khoj, start khoj would be great! That is, automatically install and start khoj server in the background.
Similar to how the Khoj Emacs package [now tries to automatically install, start and configure khoj server](https://github.com/debanjum/khoj/pull/193). (It needs testing across different operating systems, setups though)

**Comment by debanjum** [comment]
#228 should provide a more comfortable UI for configuring khoj (rather than manually editing khoj.yml).
Open to suggestions for improving usability if this feels insufficient.
