### ISSUE TITLE
Backend install stuck on - Preparing wheel metadata

### ISSUE THREAD

**Issue by ritual84** [debanjum/khoj#217]
python3 -m pip install khoj-assistant && khoj --no-gui
Collecting khoj-assistant
  Using cached https://files.pythonhosted.org/packages/e6/dd/90e159b3fad424fbbc52c48dca1be61bb5971d6bea80b140b91f114bdb50/khoj_assistant-0.6.2-py3-none-any.whl
Collecting aiohttp==3.8.4 (from khoj-assistant)
  Using cached https://files.pythonhosted.org/packages/0f/30/f00e6c3dd65087ad402e1d5e94ddd54758803b88fc3902a8ad14ac970efa/aiohttp-3.8.4-cp38-cp38-macosx_10_9_x86_64.whl
Collecting pyqt6==6.3.1 (from khoj-assistant)
  Using cached https://files.pythonhosted.org/packages/a3/ab/c5989de70eceed91abf5f828d99817462ff75f41558e9f5a6f5213f0932c/PyQt6-6.3.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... -

**Comment by debanjum** [comment]
Hey @ritual84, it looks like you got stuck while installing the PyQT khoj backend dependencies. 
- How long did it get stuck at that step to build the PyQT wheel? It can sometimes take a while to build wheels of bigger dependencies like PyQT. So waiting for a bit to see if the step completes (or errors out) may be useful
- If that doesn't work maybe retry running `python3 -m pip install khoj-assistant` a few times (and ensure you're on a stable internet connection) to see if it fixes your issue?
- Also could you confirm your OS version, python version. From the logs you shared it seems like you're on MacOS Maverick and using Python 3.8?

**Comment by debanjum** [comment]
Closing this issue for now. @ritual84, Feel free to re-open it if you were able to try above steps and couldn't still get it to work
