### ISSUE TITLE
Investigate PDF indexing use case in conjunction with chat

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#222]
I find that the search endpoint returns good enough results with my indexed PDFs without re-ranking. With re-ranking, it removes the results. Is this a concern based on the types of PDFs I'm indexing? Or is this generally an issue with PDF data, as some (especially forms) are tabular data? Should chat with the PDF endpoint skip re-ranking?

**Comment by sabaimran** [comment]
When using more formal research-style papers (which would evidently be using natural language), the chat functionality works in the way that it's expected. In fact, the user experience for chat is remarkably better than search for PDFs in particular because the data formatting after translation can be a bit wonky.

**Comment by debanjum** [comment]
Does disabling rerank for search on PDF files seem to affect the quality of the chat or search results when working with these research paper PDFs?

**Comment by debanjum** [comment]
@sabaimran, can this issue be closed if the investigation is complete?

**Comment by sabaimran** [comment]
Right, this seems like a sufficient exploration. Looks like the use case is better for PDFs that have textual data; not as capable at handling tabular information. For example, it might not be too good at processing your W2, but it can read a research paper fairly well.
