### ISSUE TITLE
Prompt exceeding max prompt size returns validation error

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#223]
When I have a result from my notes passed to Open AI that exceeds the size of the maximum prompt length, I get the following error:
```
1 validation error for ChatMessage
content
  str type expected (type=type_error.str)
```

**Comment by krrishdholakia** [comment]
@sabaimran 

would recommend using a library like `reliableGPT` to help handle this. 

It switches models in case of context window issues (e.g. to `gpt-3.5-turbo-16k` or `gpt-4`). 

Integration code is 1 line: 

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...) 
```

Source: https://github.com/BerriAI/reliableGPT
