### ISSUE TITLE
Add semantic search to Panchayat

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#4]
See: https://gitlab.com/haletic/panchayat.
Some indexing is being done on Google for public pages, but private pages are un-indexed.

**Comment by sabaimran** [comment]
Got an initial version of search working for Panchayat, but found that the solution for supporting it is actually quite bespoke. Deserializing the Yaml file requires knowledge (and object implementation) of the underlying types, and extraction of entries requires parsing of the specific `Post` objects. The separation between Khoj and Panchayat wouldn't be quite as neat as I was hoping it would.

Potential design for addressing this issue:
- Khoj allows users to pass in `object_to_jsonl` processors. When specified, these are automatically exposed as search types across Khoj. The processor handles all of the raw data deserialization and entry extraction, packaging the data into a jsonl object and passing it back to Khoj.

This allows us to extend Khoj with a sort of "Plugin" model, where users can implement their bespoke search needs without having to jump into the Khoj source code.

**Comment by sabaimran** [comment]
One open question around the plugin model is how dependency-management of plugins should be handled. For example, the plugin being used may need some package x, which is not included in khoj. This is fine if it is a standalone service, but these plugins wouldn't be. Hence, I think whatever plugin design we go with may have to have a top level `requirements.txt` or `environment.yml`, and khoj should install these during setup.

Some relevant reading on Python-Plugin architecture:
- https://mwax911.medium.com/building-a-plugin-architecture-with-python-7b4ab39ad4fc
- https://dev.to/charlesw001/plugin-architecture-in-python-jla

**Comment by sabaimran** [comment]
A bespoke solution in this branch -- https://github.com/debanjum/khoj/tree/saba/yaml-support

**Comment by sabaimran** [comment]
Refer instead to branch https://github.com/debanjum/khoj/tree/panchayat

**Comment by debanjum** [comment]
The initial version of it is completed in [Panchayat MR #95](https://gitlab.com/haletic/panchayat/-/merge_requests/95)
