### ISSUE TITLE
Use Pydantic Validators to add more input validation for the Config base model

### ISSUE THREAD

**Issue by sabaimran** [debanjum/khoj#8]
- Refer to the [Pydantic Validators](https://pydantic-docs.helpmanual.io/usage/validators/) documentation.

**Comment by sabaimran** [comment]
After #7 is completed.

**Comment by debanjum** [comment]
Resolved in f78d6ae754c44d6bed67aa7ca68d95fe8c17b827. Throw validation error if neither `input_filter` nor `input_files` fields are set in `content_type.<text_search>`
