### ISSUE TITLE
Add Configuration Flag to Index Entries with Empty Body

### ISSUE THREAD

**Issue by debanjum** [debanjum/khoj#87]
- Currently entries with only headings and no body are not indexed
- Once we do start to index entries with no body, a filter to exclude such entries would be preferable
- This will increase the flexibility of `khoj` to work for more use-cases

See the discussion on #83 for more details

**Comment by emacsomancer** [comment]
This seems to work, but the ability to index these entries is highly desirable.

**Comment by debanjum** [comment]
Updating issue to use a configuration flag to set via `khoj.yml` to allow indexing entries with empty bodies. This seems like a cleaner solution than using a query time filter which would require user input on every query and needlessly increase indexing load

**Comment by debanjum** [comment]
@emacsomancer you should now be able to index entries empty body. You'll need to set `index_heading_entries` field to `true` in your `~/.khoj/khoj yml`. Sample screenshot shared below for reference. Let me know if it doesn't work for you
<img width="227" alt="Set index_heading_entries field to true in khoj yml" src="https://user-images.githubusercontent.com/6413477/189531505-cd74ebc3-029f-4f1f-aee9-05dec7ae9568.png">
