### ISSUE TITLE
Support adding Directory of org files

### ISSUE THREAD

**Issue by bradydonald** [debanjum/khoj#92]
I use a hierarchical org set up like below. Khoj configuration requires selecting individual org files vs a directory with recursive addition of contained org files. Please consider adding.

OrgDocuments/
  Personal/
    many org files
    roam/
      many org files
  Work/
    many org files
    roam/
      man-org-files

**Comment by debanjum** [comment]
1. You can  set `input-filter` to `/path/to/notes/*.org` in `~/.khoj/khoj.yml`. See [khoj_sample.yml](https://github.com/debanjum/khoj/blob/master/config/khoj_sample.yml#L4) for example. This field is not exposed in the desktop GUI yet
2. Ability to set multiple input filters is being tracked in https://github.com/debanjum/khoj/issues/84

Once that is resolved you should be able to use `input-files` and `input-filter` fields in your `khoj.yml` to specify a combination of directories and files. Feel free to re-open this issue if the tracked and existing capabilities feel insufficient.
