### ISSUE TITLE
Set Results Count from Web Interface

### ISSUE THREAD

**Issue by debanjum** [debanjum/khoj#96]
- The Backend API supports passing count of results to be returned by settings query param. 
   E.g `http://<khoj-url/search?&n=<results_count>`
- The user interfaces need to allow users to configure this field for search

**Comment by yantar92** [comment]
For larger number of the results, it may also be useful to compact the display. For example, long heading bodies may be shortened to display only the matching parts.

**Comment by debanjum** [comment]
> For larger number of the results, it may also be useful to compact the display. 

Being able to show more results on screen would be useful for sure. Will have to think about how best to do it. 

> For example, long heading bodies may be shortened to display only the matching parts.

Currently the model matches on the entire entry. Finding the subsection of an entry best matching the query requires additional compute. This will affect latency of query and/or indexing. 

But can try find less intensive ways of compacting display to render more results on single screen

**Comment by yantar92** [comment]
> But can try find less intensive ways of compacting display to render more results on single screen

The heading body may simply be hidden behind a spoiler.

**Comment by debanjum** [comment]
> The heading body may simply be hidden behind a spoiler.

Yeah, that maybe the easiest. Or have text after the first N characters/lines hidden/folded behind a *...Show More*
